#!/bin/bash

# Detect session
if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
  TERMINAL="foot"
  LOCK="swaylock"
  LOGOUT="swaymsg exit"
else
  TERMINAL="alacritty"
  LOCK="xflock4"
  LOGOUT="xfce4-session-logout"
fi

# Main menu
choice=$(printf "  Terminal
  Files
󰀻  Applications
  Fastfetch
  System
  Audio
  Network
  Power" | rofi -dmenu -i -p "Menu")

case "$choice" in
"  Terminal")
  $TERMINAL
  ;;

"  Files")
  nautilus
  ;;

"󰀻  Applications")
  rofi -show drun -show-icons
  ;;

"  Fastfetch")
  # Fastfetch submenu with Default first
  ff_choice=$(printf "  Default
󰣇  Arch Linux
  Ubuntu
  Debian
  Fedora
  Manjaro
  Pop!_OS
  openSUSE
  Gentoo
  Linux Mint
  Custom ASCII File" | rofi -dmenu -i -p "Fastfetch")

  case "$ff_choice" in
  "  Default")
    $TERMINAL -e sh -c "fastfetch; read -n 1 -s -r -p 'Press any key to exit...'"
    ;;
  "󰣇  Arch Linux" | "")
    $TERMINAL -e sh -c "fastfetch -l arch; read -n 1 -s -r -p 'Press any key to exit...'"
    ;;
  "  Ubuntu")
    $TERMINAL -e sh -c "fastfetch -l ubuntu; read -n 1 -s -r -p 'Press any key to exit...'"
    ;;
  "  Debian")
    $TERMINAL -e sh -c "fastfetch -l debian; read -n 1 -s -r -p 'Press any key to exit...'"
    ;;
  "  Fedora")
    $TERMINAL -e sh -c "fastfetch -l fedora; read -n 1 -s -r -p 'Press any key to exit...'"
    ;;
  "  Manjaro")
    $TERMINAL -e sh -c "fastfetch -l manjaro; read -n 1 -s -r -p 'Press any key to exit...'"
    ;;
  "  Pop!_OS")
    $TERMINAL -e sh -c "fastfetch -l pop; read -n 1 -s -r -p 'Press any key to exit...'"
    ;;
  "  openSUSE")
    $TERMINAL -e sh -c "fastfetch -l opensuse; read -n 1 -s -r -p 'Press any key to exit...'"
    ;;
  "  Gentoo")
    $TERMINAL -e sh -c "fastfetch -l gentoo; read -n 1 -s -r -p 'Press any key to exit...'"
    ;;
  "  Linux Mint")
    $TERMINAL -e sh -c "fastfetch -l linuxmint; read -n 1 -s -r -p 'Press any key to exit...'"
    ;;
  "  Custom ASCII File")
    ascii_file=$(rofi -dmenu -i -p "ASCII file path (add your custom path to ts)")
    [ -f "$ascii_file" ] && $TERMINAL -e sh -c "fastfetch -i $ascii_file; read -n 1 -s -r -p 'Press any key to exit...'"
    ;;
  esac
  ;;

"  System")
  sub=$(printf "  Bluetooth
  Settings
  System Monitor" | rofi -dmenu -i -p "System")
  case "$sub" in
  "  Bluetooth") blueman-manager ;;
  "  Settings") xfce4-settings-manager ;;
  "  System Monitor") xfce4-taskmanager ;;
  esac
  ;;

"  Audio")
  sub=$(printf "  Volume Control
  Microphone" | rofi -dmenu -i -p "Audio")
  case "$sub" in
  "  Volume Control") pavucontrol ;;
  "  Microphone") pavucontrol ;;
  esac
  ;;

"  Network")
  nm-connection-editor
  ;;

"  Power")
  sub=$(printf "  Lock
  Logout
  Reboot
  Shutdown" | rofi -dmenu -i -p "Power")
  case "$sub" in
  "  Lock") $LOCK ;;
  "  Logout") $LOGOUT ;;
  "  Reboot") systemctl reboot ;;
  "  Shutdown") systemctl poweroff ;;
  esac
  ;;
esac
